spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://172.16.121.77:3306/judgements?useSSL=false&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/judgements?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    #password: '!root'
    password: 123456
    druid:
      initial-size: 30
      min-idle: 1
      max-active: 40
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-bo'row: false
      test-on-return: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 10
  application:
    name: reptile
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
logging:
  file:
    max-history: 30
    max-size: 10MB
    name: ./log/${spring.application.name}.log
  level:
    cn:
      com.ping.reptile: info
    root: info
custom:
  id: 1
  category: 1
  intervalDays: 15
  min: 7
  max: 20
server:
  port: 8001